version: '3.8'

services:
  mongodb:
    image: mongo:8.0
    container_name: mongodb_app
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: better_db
    ports:
      - 27017:27017
    volumes:
      - mongodb_data:/data/db
      - ./mongodb/init:/docker-entrypoint-initdb.d
    networks:
      - app_network
    command: mongod --bind_ip_all --port 27017
    healthcheck:
      test: mongosh --eval 'db.runCommand("ping").ok' --quiet
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 40s

  redis:
    image: 'redis:7.2-alpine'
    container_name: redis_app
    restart: always
    ports:
      - '6379:6379'
    volumes:
      - redis_data:/data
    command: redis-server --save 20 1 --loglevel warning --requirepass redis_password
    networks:
      - app_network
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']
      interval: 5s
      timeout: 3s
      retries: 5

  main:
    build:
      context: .
      dockerfile: Dockerfile
      target: ${NODE_ENV:-production}
    container_name: main_app
    restart: always
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=${NODE_ENV:-production}
      - MONGODB_URI=mongodb://admin:password@mongodb:27017/better_db?authSource=admin
      - REDIS_URL=redis://:redis_password@redis:6379
    volumes:
      - .:/app
      # - node_modules:/app/node_modules
    depends_on:
      mongodb:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - app_network

volumes:
  mongodb_data:
    driver: local
  redis_data:
    driver: local
  node_modules:
    driver: local

networks:
  app_network:
    driver: bridge
